const double minMarginBtwnAdjElems = 12;
const double screenLeftRightMargin = 24; // make 24 for ipad?
const double screenTopMargin = 54; // accounts for iphone notch/dynamic island
const double minButtonPadding = 10;
const double minMarginBelowNavBar = 56; // can be at 64 or 80?
const double minOverlayHorizontalPadding = 20; // 16?
const double minMarginBelowFields = 40; // same as below navbar, at least 48?
const double reducedMarginBelowNavBar = 40;
const double reducedMarginBelowFields = 24;
