const double buttonHeightOnPhone = 42; // 48?
const double minButtonWidthOnPhone = 92; // minTabWithOnPhone
const double reducedButtonWidthOnPhone = 72;
const double numberInputMinSizeOnPhone = 128; // displaysMinSizeOnPhone
const double buttonCornerRadiusScale = 0.5;
const double buttonCornerRadiusOnPhone = 21; // 42 * 0.5
const double fieldCornerRadiusScale = 0.0833; // 1/12
const double fieldCornerRadiusOnPhone = 10.667; // 128 * 1/12
const double numPadButtonSize = 60;
